-- Estrutura do banco do Portal de Solicitações (card BD-02).
-- Gerado com `python manage.py sqlmigrate`, a partir das migrations dos apps
-- usuarios e solicitacoes. Aplique nesta ordem num banco PostgreSQL vazio:
--   psql "$DATABASE_URL" -f database/schema.sql
-- Para criar a estrutura completa do Django (inclui admin e auth), prefira
-- `python manage.py migrate`. Os dados de demonstração estão em seed.sql.

-- ---------------------------------------------------------------------
-- usuarios · migration 0001_initial
-- ---------------------------------------------------------------------
BEGIN;
--
-- Create model Usuario
--
CREATE TABLE "usuarios" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nome" varchar(150) NOT NULL, "login" varchar(50) NOT NULL UNIQUE, "senha_hash" varchar(128) NOT NULL, "papel" varchar(20) DEFAULT 'SOLICITANTE' NOT NULL, "ativo" boolean DEFAULT true NOT NULL, "administrador" boolean DEFAULT false NOT NULL, "criado_em" timestamp with time zone DEFAULT (STATEMENT_TIMESTAMP()) NOT NULL, "ultimo_acesso" timestamp with time zone NULL);
ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_papel_valido" CHECK ("papel" IN ('SOLICITANTE', 'ATENDENTE'));
CREATE INDEX "usuarios_login_2172a8dc_like" ON "usuarios" ("login" varchar_pattern_ops);
COMMIT;

-- ---------------------------------------------------------------------
-- solicitacoes · migration 0001_initial (categorias, solicitacoes, historico_status)
-- ---------------------------------------------------------------------
BEGIN;
--
-- Create model Categoria
--
CREATE TABLE "categorias" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nome" varchar(60) NOT NULL UNIQUE, "ativa" boolean DEFAULT true NOT NULL);
--
-- Create model Solicitacao
--
CREATE TABLE "solicitacoes" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "titulo" varchar(150) NOT NULL, "descricao" varchar(2000) NOT NULL, "status" varchar(20) DEFAULT 'ABERTO' NOT NULL, "criado_em" timestamp with time zone DEFAULT (STATEMENT_TIMESTAMP()) NOT NULL, "atualizado_em" timestamp with time zone DEFAULT (STATEMENT_TIMESTAMP()) NOT NULL, "categoria_id" bigint NOT NULL, "solicitante_id" bigint NOT NULL);
--
-- Create model HistoricoStatus
--
CREATE TABLE "historico_status" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "status_anterior" varchar(20) NULL, "status_novo" varchar(20) NOT NULL, "alterado_em" timestamp with time zone DEFAULT (STATEMENT_TIMESTAMP()) NOT NULL, "alterado_por_id" bigint NOT NULL, "solicitacao_id" bigint NOT NULL);
--
-- Create index solicitacoes_status_idx on field(s) status of model solicitacao
--
CREATE INDEX "solicitacoes_status_idx" ON "solicitacoes" ("status");
--
-- Create index solicitacoes_criado_em_idx on field(s) criado_em of model solicitacao
--
CREATE INDEX "solicitacoes_criado_em_idx" ON "solicitacoes" ("criado_em");
--
-- Create constraint solicitacoes_titulo_minimo on model solicitacao
--
ALTER TABLE "solicitacoes" ADD CONSTRAINT "solicitacoes_titulo_minimo" CHECK (LENGTH(TRIM("titulo")) >= 3);
--
-- Create constraint solicitacoes_descricao_minima on model solicitacao
--
ALTER TABLE "solicitacoes" ADD CONSTRAINT "solicitacoes_descricao_minima" CHECK (LENGTH(TRIM("descricao")) >= 10);
--
-- Create constraint solicitacoes_status_valido on model solicitacao
--
ALTER TABLE "solicitacoes" ADD CONSTRAINT "solicitacoes_status_valido" CHECK ("status" IN ('ABERTO', 'EM_ATENDIMENTO', 'CONCLUIDO'));
--
-- Create index historico_solicitacao_idx on field(s) solicitacao, alterado_em of model historicostatus
--
CREATE INDEX "historico_solicitacao_idx" ON "historico_status" ("solicitacao_id", "alterado_em");
--
-- Create constraint historico_status_anterior_valido on model historicostatus
--
ALTER TABLE "historico_status" ADD CONSTRAINT "historico_status_anterior_valido" CHECK (("status_anterior" IS NULL OR "status_anterior" IN ('ABERTO', 'EM_ATENDIMENTO', 'CONCLUIDO')));
--
-- Create constraint historico_status_novo_valido on model historicostatus
--
ALTER TABLE "historico_status" ADD CONSTRAINT "historico_status_novo_valido" CHECK ("status_novo" IN ('ABERTO', 'EM_ATENDIMENTO', 'CONCLUIDO'));
--
-- Create constraint historico_status_muda on model historicostatus
--
ALTER TABLE "historico_status" ADD CONSTRAINT "historico_status_muda" CHECK (("status_anterior" IS NULL OR NOT ("status_anterior" = ("status_novo") AND "status_anterior" IS NOT NULL)));
CREATE INDEX "categorias_nome_27339996_like" ON "categorias" ("nome" varchar_pattern_ops);
ALTER TABLE "solicitacoes" ADD CONSTRAINT "solicitacoes_categoria_id_6649898a_fk_categorias_id" FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "solicitacoes" ADD CONSTRAINT "solicitacoes_solicitante_id_3b99045a_fk_usuarios_id" FOREIGN KEY ("solicitante_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "solicitacoes_categoria_id_6649898a" ON "solicitacoes" ("categoria_id");
CREATE INDEX "solicitacoes_solicitante_id_3b99045a" ON "solicitacoes" ("solicitante_id");
ALTER TABLE "historico_status" ADD CONSTRAINT "historico_status_alterado_por_id_3b6a627d_fk_usuarios_id" FOREIGN KEY ("alterado_por_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "historico_status" ADD CONSTRAINT "historico_status_solicitacao_id_16fdf7be_fk_solicitacoes_id" FOREIGN KEY ("solicitacao_id") REFERENCES "solicitacoes" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "historico_status_alterado_por_id_3b6a627d" ON "historico_status" ("alterado_por_id");
COMMIT;
