# Generated by Django 5.2.17 on 2026-10-02 17:57

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=60, unique=True)),
                ("ativa", models.BooleanField(db_default=True, default=True)),
            ],
            options={
                "db_table": "categorias",
            },
        ),
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descricao", models.CharField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("EM_ATENDIMENTO", "Em Atendimento"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        db_default=models.Value("ABERTO"),
                        default="ABERTO",
                        max_length=20,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitacoes",
                        to="solicitacoes.categoria",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "solicitacoes",
            },
        ),
        migrations.CreateModel(
            name="HistoricoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("EM_ATENDIMENTO", "Em Atendimento"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("EM_ATENDIMENTO", "Em Atendimento"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "alterado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alteracoes_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="solicitacoes.solicitacao",
                    ),
                ),
            ],
            options={
                "db_table": "historico_status",
            },
        ),
        migrations.AddIndex(
            model_name="solicitacao",
            index=models.Index(fields=["status"], name="solicitacoes_status_idx"),
        ),
        migrations.AddIndex(
            model_name="solicitacao",
            index=models.Index(fields=["criado_em"], name="solicitacoes_criado_em_idx"),
        ),
        migrations.AddConstraint(
            model_name="solicitacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    django.db.models.lookups.GreaterThanOrEqual(
                        django.db.models.functions.text.Length(
                            django.db.models.functions.text.Trim("titulo")
                        ),
                        3,
                    )
                ),
                name="solicitacoes_titulo_minimo",
            ),
        ),
        migrations.AddConstraint(
            model_name="solicitacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    django.db.models.lookups.GreaterThanOrEqual(
                        django.db.models.functions.text.Length(
                            django.db.models.functions.text.Trim("descricao")
                        ),
                        10,
                    )
                ),
                name="solicitacoes_descricao_minima",
            ),
        ),
        migrations.AddConstraint(
            model_name="solicitacao",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ABERTO", "EM_ATENDIMENTO", "CONCLUIDO"])),
                name="solicitacoes_status_valido",
            ),
        ),
        migrations.AddIndex(
            model_name="historicostatus",
            index=models.Index(
                fields=["solicitacao", "alterado_em"], name="historico_solicitacao_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="historicostatus",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status_anterior__isnull", True),
                    ("status_anterior__in", ["ABERTO", "EM_ATENDIMENTO", "CONCLUIDO"]),
                    _connector="OR",
                ),
                name="historico_status_anterior_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicostatus",
            constraint=models.CheckConstraint(
                condition=models.Q(("status_novo__in", ["ABERTO", "EM_ATENDIMENTO", "CONCLUIDO"])),
                name="historico_status_novo_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicostatus",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status_anterior__isnull", True),
                    models.Q(("status_anterior", models.F("status_novo")), _negated=True),
                    _connector="OR",
                ),
                name="historico_status_muda",
            ),
        ),
    ]
