# Generated by Django 5.2.17 on 2026-10-02 17:57

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("login", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(db_column="senha_hash", max_length=128)),
                (
                    "papel",
                    models.CharField(
                        choices=[("SOLICITANTE", "Solicitante"), ("ATENDENTE", "Atendente")],
                        db_default=models.Value("SOLICITANTE"),
                        default="SOLICITANTE",
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(db_default=True, default=True)),
                ("administrador", models.BooleanField(db_default=False, default=False)),
                (
                    "criado_em",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, db_column="ultimo_acesso", null=True),
                ),
            ],
            options={
                "db_table": "usuarios",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("papel__in", ["SOLICITANTE", "ATENDENTE"])),
                        name="usuarios_papel_valido",
                    )
                ],
            },
        ),
    ]
